### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [MarounMaroun/mycontribution#4]
As was [mentioned on Reddit](https://reddit.com/r/coolgithubprojects/comments/ac3tuz/view_your_github_contribution_graph_from_the/ed50817?context=3), this project is missing a LICENSE file. Please [choose a license](https://choosealicense.com/) for this project, so people know how you allow the sourcecode to be used.

**Comment by MarounMaroun** [comment]
@brylie Thanks, I'll add now.

**Comment by MarounMaroun** [comment]
Added license :)
